name: Lint

permissions:
    id-token: write
    contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow job to be triggered manually.
  workflow_dispatch:

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lint_command:
          - poe lint
          - pip-audit
    steps:
      - name: Acquire sources
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: Run code-style checks
        run: uv run ${{ matrix.lint_command }}
