name: main
run-name: main

permissions:
    id-token: write
    contents: read

env:
  POETRY_VERSION: "1.3.0"
  PYTHON_VERSION: "3.10"

on:
  pull_request: 
    branches:
     - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_IDENTITY_PROVIDER }}
          service_account: bquest-sa@oghub-bquest-dev.iam.gserviceaccount.com
          project_id: oghub-bquest-dev
      - uses: google-github-actions/setup-gcloud@v1
      - name: Setup Gcloud parameters
        run:  |
          gcloud iam service-accounts list
